---
title: "2025-11-18_first-data-wrangling"
author: "Chris"
date: "2025-11-18"
output: html_document
---


```{r include=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
```



# read the data

```{r}
df_parks <- read_csv("data/Parks_Properties_20251103.csv") |>
  select(ACQUISITIONDATE: multipolygon) |>
  clean_names() 


df_chp <- read_excel("data/2022-chp-pud.xlsx", sheet = "CHP_all_data", skip = 1) |>
  clean_names()

df_prem_death <- read_excel("data/2022-chp-pud.xlsx", sheet = "Cause_of_premature_death") |>
  clean_names()

df_cancer <- read_excel("data/2022-chp-pud.xlsx", sheet = "Cancer_data_ranked") |>
  clean_names()
```


# one park, multiple IDs

```{r}
df_parks <- 
  df_parks |>
  rename(id = communityboard) 

df_parks_commubity <-
  df_parks |>
  mutate(
    acres = as.numeric(acres),
    id = as.factor(id)
  ) |>
  group_by(id) |>
  summarise(
    sum_acres = sum(acres, na.rm = TRUE),
    mean_acres = mean(acres, na.rm = TRUE),
    n_parks = n()
  ) |>
  filter(sum_acres > 0) |> # only use observations with positive areas
  mutate(
    id = as.character(id),
    n_split = lengths(strsplit(id, ","))
  ) |>
  separate_rows(id, sep = ",") |>
  mutate(
    id = trimws(id),
    sum_acres_adj = sum_acres / n_split,
    n_parks_adj = n_parks / n_split
  ) |>
  group_by(id) |>
  summarise(
    sum_acres = sum(sum_acres_adj, na.rm = TRUE),
    n_parks = sum(n_parks_adj, na.rm = TRUE),
    mean_acres = sum_acres / n_parks
  )

df_parks_borough <-
  df_parks |>
  filter(
    borough == c("B", "M", "Q", "R", "X")
  ) |>
  mutate(
    borough = as.factor(borough),
    acres = as.numeric(acres)
  ) |>
  group_by(borough) |>
  summarise(
    sum_acres = sum(acres, na.rm = TRUE),
    mean_acres = mean(acres, na.rm = TRUE),
    n_parks = n()
  ) |>
  rename(id = borough)

df_parks_all_dist <-
  bind_rows(df_parks_borough, df_parks_commubity)

```



```{r}
# df_parks_split <-
#   df_parks_all_dist |>
#   mutate(
#     id = as.character(id),
#     n_split = lengths(strsplit(id, ","))
#   ) |>
#   separate_rows(id, sep = ",") |>
#   mutate(
#     id = trimws(id),
#     sum_acres_adj = sum_acres / n_split,
#     n_parks_adj = n_parks / n_split
#   ) |>
#   group_by(id) |>
#   summarise(
#     sum_acres = sum(sum_acres_adj, na.rm = TRUE),
#     n_parks = sum(n_parks_adj, na.rm = TRUE),
#     mean_acres = sum_acres / n_parks
#   )
```


# combine the area df into the chp-pud

```{r}
# get rid of reliability index

df_chp_clean <- df_chp |>
  select(-contains("95cl"), -contains("nyc_comparison"), -contains("reliability_note"))
```


```{r}
# create a variable map for df_chp_clean
var_map <- tribble(
  ~variable,                 ~category,
  
  "id",                      "geo",
  "borough",                 "geo",
  "name",                    "geo",
  "overall_pop",             "population",

  
  "race_white",              "demographic_race",
  "race_black",              "demographic_race",
  "race_latino",             "demographic_race",
  "race_asian",              "demographic_race",
  "race_other",              "demographic_race",
  "age0to17",                "demographic_age",
  "age18to24",               "demographic_age",
  "age25to44",               "demographic_age",
  "age45to64",               "demographic_age",
  "age65plus",               "demographic_age",
  "born_outside_us",         "demographic_migration",
  "ltd_eng_prof",            "demographic_language",

  
  "edu_did_not_complete_hs",      "SES_education",
  "edu_hs_grad_some_college",     "SES_education",
  "edu_college_degree_and_higher","SES_education",
  "poverty",                      "SES_economic",
  "unemployment",                 "SES_economic",
  "rent_burden",                  "SES_economic",
  "school_absent",                "education_outcome",
  "on_time_hs_grad",              "education_outcome",

 
  "homes_ac",                     "housing_environment",
  "homes_no_defects",             "housing_environment",
  "air_pollution",                "physical_environment",
  "ratio_bodega_supermarket",     "food_environment",
  "farmers_markets",              "food_environment",

 
  "helpful_neighbor",             "social_environment",
  "assault_hosp",                 "safety_violence",
  "jail_incarceration",           "safety_justice",
  "pedestrian_hosp",              "safety_transport",

 
  "physical_activity",            "behavior",
  "fruit_veg",                    "behavior",
  "sugary_drink",                 "behavior",
  "smoking",                      "behavior",
  "binge_drink",                  "behavior",

  
  "uninsured",                    "access_care",
  "unmet_med_care",               "access_care",
  "hpv_vaccination_all",          "preventive_care",
  "flu_vaccination",              "preventive_care",

  
  "preterm_births",               "maternal_child",
  "teen_births",                  "maternal_child",
  "child_obesity",                "maternal_child",
  "infant_mort",                  "maternal_child",

  
  "obesity",                      "chronic_disease",
  "diabetes",                     "chronic_disease",
  "hypertension",                 "chronic_disease",
  "hiv_diagnoses",                "infectious_disease",
  "hep_c_reports",                "infectious_disease",
  "avoidable_child_hosp",         "hospitalization",
  "avoidable_adult_hosp",         "hospitalization",
  "falls_hosp",                   "injury_hospitalization",
  "psych_hosp",                   "mental_health",

  
  "avertable_death",              "mortality",
  "premature_mort_rate",          "mortality",
  "premature_mort_number",        "mortality",
  "life_expectancy",              "global_health",
  "self_rep_health",              "global_health"
)

```


```{r}
var_demo <- var_map |>
  filter(category %in% c("geo", "population", "demographic_race", "demographic_age","demographic_migration", "demographic_language")) |>
  pull(variable)

df_demographic <-
  df_chp_clean |>
  select(all_of(var_demo))

var_edu <- var_map |>
  filter(category %in% c("geo", "SES_education")) |>
  pull(variable)
  
df_education <- df_chp_clean |>
  select(all_of(var_edu)) |>
  mutate(edu_no_college_degree = edu_did_not_complete_hs + edu_hs_grad_some_college)
  
```
















