---
title: "Where the Grass is Greener: Linking Demographic and Health Outcome Data to Urban Green Space in NYC"
output: html_document
---

___

## Welcome

<script type="text/javascript" charset="UTF-8" data-locale="en" data-socrata-domain="data.cityofnewyork.us" src="https://data.cityofnewyork.us/component/visualization/v1/socrata-visualizations-loader.js"></script>
<a class="socrata-visualization-embed" data-embed-version="1" data-height="600" data-socrata-domain="data.cityofnewyork.us" data-vizcan-uid="krz2-j7bn" data-vif="{&quot;configuration&quot;:{&quot;viewSourceDataLink&quot;:true,&quot;mapCenterAndZoom&quot;:{&quot;center&quot;:{&quot;lng&quot;:-73.98257326983475,&quot;lat&quot;:40.703237772969175},&quot;zoom&quot;:9.228206019175689},&quot;basemapOptions&quot;:{&quot;searchBoundaryLowerRightLongitude&quot;:-73.70905206009107,&quot;searchBoundaryUpperLeftLongitude&quot;:-74.25609447490525,&quot;searchBoundaryUpperLeftLatitude&quot;:40.91132879994986,&quot;navigationControl&quot;:true,&quot;basemapStyle&quot;:&quot;mapbox://styles/mapbox/basic-v9&quot;,&quot;geoCoderControl&quot;:true,&quot;geoLocateControl&quot;:true,&quot;searchBoundaryLowerRightLatitude&quot;:40.49449457390966},&quot;mapPitchAndBearing&quot;:{&quot;bearing&quot;:0,&quot;pitch&quot;:0},&quot;datasetMetadata&quot;:false,&quot;panAndZoom&quot;:true,&quot;locateUser&quot;:false},&quot;series&quot;:[{&quot;unit&quot;:{&quot;other&quot;:&quot;properties&quot;,&quot;one&quot;:&quot;property&quot;},&quot;visible&quot;:true,&quot;color&quot;:{&quot;primary&quot;:&quot;#eb6900&quot;},&quot;mapOptions&quot;:{&quot;shapeOutlineColor&quot;:&quot;#31a75a&quot;,&quot;simplificationLevel&quot;:&quot;2&quot;,&quot;mapFlyoutTitleColumnName&quot;:&quot;signname&quot;,&quot;shapeFillOpacity&quot;:50,&quot;mapType&quot;:&quot;boundaryMap&quot;,&quot;shapeFillColor&quot;:&quot;#31a75a&quot;,&quot;shapeOutlineWidth&quot;:1},&quot;showLegend&quot;:true,&quot;type&quot;:&quot;map&quot;,&quot;dataSource&quot;:{&quot;measure&quot;:{&quot;aggregationFunction&quot;:&quot;count&quot;},&quot;name&quot;:&quot;Parks Properties&quot;,&quot;type&quot;:&quot;socrata.soql&quot;,&quot;datasetUid&quot;:&quot;enfh-gkve&quot;,&quot;dimension&quot;:{&quot;columnName&quot;:&quot;multipolygon&quot;,&quot;aggregationFunction&quot;:null},&quot;filters&quot;:[]},&quot;primary&quot;:true,&quot;label&quot;:null}],&quot;format&quot;:{&quot;type&quot;:&quot;visualization_interchange_format&quot;,&quot;version&quot;:3},&quot;description&quot;:&quot;&quot;,&quot;id&quot;:&quot;0a3a6228-e34e-4092-81bc-1950aac8a6ee&quot;,&quot;title&quot;:&quot;&quot;,&quot;currentMapLayerIndex&quot;:0}" data-width="800" href="https://data.cityofnewyork.us/Recreation/Parks-Properties/enfh-gkve?referrer=embed" rel="external" target="_blank">View the data</a>

Map of NYC Parks Properties from NYC Open Data https://data.cityofnewyork.us/Recreation/Parks-Properties-Map/krz2-j7bn

___

## About Our Project



___

## Screencast